/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Cliente;
import entidade.ManterCliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 202211697
 */
public class ListarClientesView extends javax.swing.JFrame {

    /**
     * Creates new form FormPesquisar
     */
    public ListarClientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTpesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTaluno = new javax.swing.JTable();
        jRdesc = new javax.swing.JRadioButton();
        jRasc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setText("Digite o Código para pesquisar :");

        jTpesquisar.setColumns(5);
        jTpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpesquisarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTaluno.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jTaluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email", "Endereço", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTaluno);
        if (jTaluno.getColumnModel().getColumnCount() > 0) {
            jTaluno.getColumnModel().getColumn(0).setResizable(false);
            jTaluno.getColumnModel().getColumn(1).setResizable(false);
            jTaluno.getColumnModel().getColumn(2).setResizable(false);
            jTaluno.getColumnModel().getColumn(4).setResizable(false);
        }

        buttonGroup1.add(jRdesc);
        jRdesc.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRdesc.setForeground(new java.awt.Color(0, 0, 102));
        jRdesc.setText("Decrescente");
        jRdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdescActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRasc);
        jRasc.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRasc.setForeground(new java.awt.Color(0, 0, 102));
        jRasc.setText("Ascendente");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Listagem : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jRdesc)
                        .addGap(52, 52, 52)
                        .addComponent(jRasc)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdesc)
                    .addComponent(jRasc)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            Cliente a = new Cliente();
            ManterCliente ca = new ManterCliente();
            
            DefaultTableModel alunopesque = (DefaultTableModel) jTaluno.getModel();
            
            if (jTpesquisar.getText().equalsIgnoreCase("")){
                
                if(jRdesc.isSelected()){
                
                ArrayList<Cliente> alunos = ca.PesquisarTudoDesc();
                
                for (int i = 0; i < alunos.size(); i++){
                    a = alunos.get(i);
                    alunopesque.addRow(new Object[] {a.getCodigo(),a.getNome(),a.getEmail(),a.getEndereco(),a.getTelefone()});
                } 
                
                }else if (jRasc.isSelected()){
                
                ArrayList<Cliente> alunos = ca.PesquisarTudo();
                
                for (int i = 0; i < alunos.size(); i++){
                    a = alunos.get(i);
                    alunopesque.addRow(new Object[] {a.getCodigo(),a.getNome(),a.getEmail(),a.getEndereco(),a.getTelefone()});
                }
                
                
                }
                ArrayList<Cliente> alunos = ca.PesquisarTudo();
                
                for (int i = 0; i < alunos.size(); i++){
                    a = alunos.get(i);
                    alunopesque.addRow(new Object[] {a.getCodigo(),a.getNome(),a.getEmail(),a.getEndereco(),a.getTelefone()});
                }
            }else{
                a.setCodigo(Integer.parseInt(jTpesquisar.getText()));
                  ArrayList<Cliente> alunos = ca.pesquisarRegistro(a);
                for (Cliente aluno : alunos) {
            alunopesque.addRow(new Object[]{aluno.getCodigo(), aluno.getNome(), aluno.getEmail(),aluno.getEndereco(),aluno.getTelefone()});
        } 
            }
            
            jTpesquisar.setText(null);
            jTpesquisar.requestFocus();
            
            }
            
            catch (Exception e){
                System.out.println("Erro" + e.getMessage());
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpesquisarActionPerformed

    private void jRdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRasc;
    private javax.swing.JRadioButton jRdesc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTaluno;
    private javax.swing.JTextField jTpesquisar;
    // End of variables declaration//GEN-END:variables
}
